language: c
compiler:
  - gcc
script: make test
before_install:
    - script/bootstrap.sh
    - cd src
env:
  global:
    secure: "Duzvup1uIyI+GMw22CvQjuQzFL8Y7IebjkOTokOtrKR25qqrZgpRsqqsCO7r\nfIwr4MkKk7r1ZA+WUQNsuegsvrroe1oC9ZSVgSYDcj9H88b6qCPaYafO0L0G\ntlQeoeRzDqSOjKImvLYzD4qlI1+CTA7rG0me+wxZJ3LxuHu3NTs="
notifications:
  hipchat: <%= ENV['HIPCHAT_TOKEN'] %>@Ford
