/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-1-26:  2h:51m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .h files for avr */
#ifdef _ATS_AVR
#include "ats/basics.h"
#endif /* _ATS_AVR */
/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from ally loaded files */
/* external codes at top */

#include "ats/basics.h"

typedef struct {
    void *bus;
    uint32_t id;
    uint64_t data;
} CanMessage;

typedef struct {
    int i;
    char bytes[8];
} test_t;

/* type definitions */
typedef struct {
ats_int_type atslab_head ;
ats_int_type atslab_tail ;
ats_int_type atslab_max ;
ats_var_type atslab_elements[] ;
} anairiats_rec_0 ;

/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_nmod) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ieq) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, get_queue) () ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2SATS_2queue_2esats__sasp__queue = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */

ats_void_type queue_init_01931_uint8_t (ats_ref_type arg0) ;

ats_bool_type queue_push_01928_uint8_t (ats_ref_type arg0, uint8_t arg1) ;

uint8_t queue_pop_01929_uint8_t (ats_ref_type arg0) ;

ats_int_type queue_length_01932_uint8_t (ats_ref_type arg0) ;

ats_bool_type queue_full_01934_uint8_t (ats_ref_type arg0) ;

ats_bool_type queue_available_01933_uint8_t (ats_ref_type arg0) ;

ats_bool_type queue_empty_01935_uint8_t (ats_ref_type arg0) ;

ats_void_type queue_snapshot_01936_uint8_t (ats_ref_type arg0, ats_ref_type arg1) ;

uint8_t queue_peek_01930_uint8_t (ats_ref_type arg0) ;

ats_void_type queue_init_01931_int (ats_ref_type arg0) ;

ats_bool_type queue_push_01928_int (ats_ref_type arg0, int arg1) ;

int queue_pop_01929_int (ats_ref_type arg0) ;

ats_int_type queue_length_01932_int (ats_ref_type arg0) ;

ats_bool_type queue_full_01934_int (ats_ref_type arg0) ;

ats_bool_type queue_available_01933_int (ats_ref_type arg0) ;

ats_bool_type queue_empty_01935_int (ats_ref_type arg0) ;

ats_void_type queue_snapshot_01936_int (ats_ref_type arg0, ats_ref_type arg1) ;

int queue_peek_01930_int (ats_ref_type arg0) ;

ats_void_type queue_init_01931_CanMessage (ats_ref_type arg0) ;

ats_bool_type queue_push_01928_CanMessage (ats_ref_type arg0, CanMessage arg1) ;

CanMessage queue_pop_01929_CanMessage (ats_ref_type arg0) ;

ats_int_type queue_length_01932_CanMessage (ats_ref_type arg0) ;

ats_bool_type queue_full_01934_CanMessage (ats_ref_type arg0) ;

ats_bool_type queue_available_01933_CanMessage (ats_ref_type arg0) ;

ats_bool_type queue_empty_01935_CanMessage (ats_ref_type arg0) ;

ats_void_type queue_snapshot_01936_CanMessage (ats_ref_type arg0, ats_ref_type arg1) ;

CanMessage queue_peek_01930_CanMessage (ats_ref_type arg0) ;

ats_void_type queue_init_01931_test_t (ats_ref_type arg0) ;

ats_bool_type queue_push_01928_test_t (ats_ref_type arg0, test_t arg1) ;

test_t queue_pop_01929_test_t (ats_ref_type arg0) ;

ats_int_type queue_length_01932_test_t (ats_ref_type arg0) ;

ats_bool_type queue_full_01934_test_t (ats_ref_type arg0) ;

ats_bool_type queue_available_01933_test_t (ats_ref_type arg0) ;

ats_bool_type queue_empty_01935_test_t (ats_ref_type arg0) ;

ats_void_type queue_snapshot_01936_test_t (ats_ref_type arg0, ats_ref_type arg1) ;

test_t queue_peek_01930_test_t (ats_ref_type arg0) ;

ats_void_type dummy_0 () ;

/* partial value template declarations */
/*  temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1015(line=58, offs=32) -- 1049(line=60, offs=2)
*/

ats_void_type
queue_init_01931_uint8_t (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp4) ;

__ats_lab_queue_init_01931_uint8_t:
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = 0 ;
return /* (tmp4) */ ;
} /* end of [queue_init_01931_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 564(line=37, offs=32) -- 748(line=46, offs=4)
*/

ats_bool_type
queue_push_01928_uint8_t (ats_ref_type arg0, uint8_t arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp6) ;
ATSlocal (ats_int_type, tmp7) ;
ATSlocal (ats_int_type, tmp8) ;
ATSlocal (ats_int_type, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;
ATSlocal (ats_int_type, tmp11) ;
ATSlocal (ats_bool_type, tmp12) ;
ATSlocal (ats_int_type, tmp13) ;

__ats_lab_queue_push_01928_uint8_t:
tmp9 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp8 = atspre_iadd (tmp9, 1) ;
tmp11 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp10 = atspre_iadd (tmp11, 1) ;
tmp7 = atspre_nmod (tmp8, tmp10) ;
tmp13 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp12 = atspre_ieq (tmp7, tmp13) ;
if (tmp12) {
tmp6 = ats_false_bool ;
} else {
ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp7]) = arg1 ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) = tmp7 ;
tmp6 = ats_true_bool ;
} /* end of [if] */
return (tmp6) ;
} /* end of [queue_push_01928_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 780(line=48, offs=31) -- 898(line=52, offs=2)
*/

uint8_t
queue_pop_01929_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (uint8_t, tmp15) ;
ATSlocal (ats_int_type, tmp16) ;
ATSlocal (ats_int_type, tmp17) ;
ATSlocal (ats_int_type, tmp18) ;
ATSlocal (ats_int_type, tmp19) ;
ATSlocal (ats_int_type, tmp20) ;
ATSlocal (uint8_t, tmp21) ;
ATSlocal (ats_int_type, tmp22) ;

__ats_lab_queue_pop_01929_uint8_t:
tmp18 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp17 = atspre_iadd (tmp18, 1) ;
tmp20 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp19 = atspre_iadd (tmp20, 1) ;
tmp16 = atspre_nmod (tmp17, tmp19) ;
tmp22 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp21 = ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp22]) ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = tmp16 ;
tmp15 = tmp21 ;
return (tmp15) ;
} /* end of [queue_pop_01929_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1084(line=62, offs=34) -- 1191(line=66, offs=2)
*/

ats_int_type
queue_length_01932_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp26) ;
ATSlocal (ats_int_type, tmp27) ;
ATSlocal (ats_int_type, tmp28) ;
ATSlocal (ats_int_type, tmp29) ;
ATSlocal (ats_int_type, tmp30) ;
ATSlocal (ats_int_type, tmp31) ;
ATSlocal (ats_int_type, tmp32) ;

__ats_lab_queue_length_01932_uint8_t:
tmp28 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp27 = atspre_iadd (tmp28, 1) ;
tmp30 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp31 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp29 = atspre_isub (tmp30, tmp31) ;
tmp32 = atspre_iadd (tmp27, tmp29) ;
tmp26 = atspre_nmod (tmp32, tmp27) ;
return (tmp26) ;
} /* end of [queue_length_01932_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1287(line=71, offs=32) -- 1318(line=72, offs=26)
*/

ats_bool_type
queue_full_01934_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp24) ;
ATSlocal (ats_int_type, tmp25) ;
ATSlocal (ats_int_type, tmp33) ;

__ats_lab_queue_full_01934_uint8_t:
tmp25 = queue_length_01932_uint8_t (arg0) ;
tmp33 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp24 = atspre_ieq (tmp25, tmp33) ;
return (tmp24) ;
} /* end of [queue_full_01934_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1356(line=74, offs=37) -- 1388(line=75, offs=26)
*/

ats_bool_type
queue_available_01933_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp36) ;
ATSlocal (ats_int_type, tmp37) ;
ATSlocal (ats_int_type, tmp38) ;

__ats_lab_queue_available_01933_uint8_t:
tmp37 = queue_length_01932_uint8_t (arg0) ;
tmp38 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp36 = atspre_ilt (tmp37, tmp38) ;
return (tmp36) ;
} /* end of [queue_available_01933_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1225(line=68, offs=33) -- 1252(line=69, offs=22)
*/

ats_bool_type
queue_empty_01935_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp41) ;
ATSlocal (ats_int_type, tmp42) ;

__ats_lab_queue_empty_01935_uint8_t:
tmp42 = queue_length_01932_uint8_t (arg0) ;
tmp41 = atspre_ieq (tmp42, 0) ;
return (tmp41) ;
} /* end of [queue_empty_01935_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1433(line=78, offs=3) -- 1644(line=86, offs=4)
*/

ats_void_type
queue_snapshot_01936_uint8_t (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp45) ;
ATSlocal (ats_int_type, tmp46) ;
ATSlocal (ats_int_type, tmp47) ;
ATSlocal (ats_bool_type, tmp48) ;
ATSlocal (ats_int_type, tmp49) ;
ATSlocal (ats_int_type, tmp50) ;
ATSlocal (ats_int_type, tmp51) ;
ATSlocal (ats_int_type, tmp52) ;
ATSlocal (ats_int_type, tmp53) ;
ATSlocal (ats_int_type, tmp54) ;
ATSlocal (uint8_t, tmp55) ;

__ats_lab_queue_snapshot_01936_uint8_t:
tmp46 = queue_length_01932_uint8_t (arg0) ;
/* ats_int_type tmp47 ; */
/* loop initialization */
tmp47 = 0 ;
ats_loop_beg_mac(__ats_lab_0)
tmp48 = atspre_ilt (tmp47, tmp46) ;
if (!tmp48) break ;
tmp52 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp51 = atspre_iadd (tmp52, tmp47) ;
tmp54 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp53 = atspre_iadd (tmp54, 1) ;
tmp50 = atspre_nmod (tmp51, tmp53) ;
tmp55 = ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp50]) ;
ats_caselptrind_mac(uint8_t, arg1, [tmp47]) = tmp55 ;
/* post update before continue */
__ats_lab_2:
tmp49 = atspre_iadd (tmp47, 1) ;
tmp47 = tmp49 ;
ats_loop_end_mac(__ats_lab_0, __ats_lab_1)
return /* (tmp45) */ ;
} /* end of [queue_snapshot_01936_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 931(line=54, offs=32) -- 982(line=56, offs=2)
*/

uint8_t
queue_peek_01930_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (uint8_t, tmp57) ;
ATSlocal (ats_int_type, tmp58) ;

__ats_lab_queue_peek_01930_uint8_t:
tmp58 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp57 = ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp58]) ;
return (tmp57) ;
} /* end of [queue_peek_01930_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1015(line=58, offs=32) -- 1049(line=60, offs=2)
*/

ats_void_type
queue_init_01931_int (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp62) ;

__ats_lab_queue_init_01931_int:
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = 0 ;
return /* (tmp62) */ ;
} /* end of [queue_init_01931_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 564(line=37, offs=32) -- 748(line=46, offs=4)
*/

ats_bool_type
queue_push_01928_int (ats_ref_type arg0, int arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp64) ;
ATSlocal (ats_int_type, tmp65) ;
ATSlocal (ats_int_type, tmp66) ;
ATSlocal (ats_int_type, tmp67) ;
ATSlocal (ats_int_type, tmp68) ;
ATSlocal (ats_int_type, tmp69) ;
ATSlocal (ats_bool_type, tmp70) ;
ATSlocal (ats_int_type, tmp71) ;

__ats_lab_queue_push_01928_int:
tmp67 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp66 = atspre_iadd (tmp67, 1) ;
tmp69 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp68 = atspre_iadd (tmp69, 1) ;
tmp65 = atspre_nmod (tmp66, tmp68) ;
tmp71 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp70 = atspre_ieq (tmp65, tmp71) ;
if (tmp70) {
tmp64 = ats_false_bool ;
} else {
ats_caselind_mac(int, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp65]) = arg1 ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) = tmp65 ;
tmp64 = ats_true_bool ;
} /* end of [if] */
return (tmp64) ;
} /* end of [queue_push_01928_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 780(line=48, offs=31) -- 898(line=52, offs=2)
*/

int
queue_pop_01929_int (ats_ref_type arg0) {
/* local vardec */
ATSlocal (int, tmp73) ;
ATSlocal (ats_int_type, tmp74) ;
ATSlocal (ats_int_type, tmp75) ;
ATSlocal (ats_int_type, tmp76) ;
ATSlocal (ats_int_type, tmp77) ;
ATSlocal (ats_int_type, tmp78) ;
ATSlocal (int, tmp79) ;
ATSlocal (ats_int_type, tmp80) ;

__ats_lab_queue_pop_01929_int:
tmp76 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp75 = atspre_iadd (tmp76, 1) ;
tmp78 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp77 = atspre_iadd (tmp78, 1) ;
tmp74 = atspre_nmod (tmp75, tmp77) ;
tmp80 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp79 = ats_caselind_mac(int, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp80]) ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = tmp74 ;
tmp73 = tmp79 ;
return (tmp73) ;
} /* end of [queue_pop_01929_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1084(line=62, offs=34) -- 1191(line=66, offs=2)
*/

ats_int_type
queue_length_01932_int (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp84) ;
ATSlocal (ats_int_type, tmp85) ;
ATSlocal (ats_int_type, tmp86) ;
ATSlocal (ats_int_type, tmp87) ;
ATSlocal (ats_int_type, tmp88) ;
ATSlocal (ats_int_type, tmp89) ;
ATSlocal (ats_int_type, tmp90) ;

__ats_lab_queue_length_01932_int:
tmp86 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp85 = atspre_iadd (tmp86, 1) ;
tmp88 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp89 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp87 = atspre_isub (tmp88, tmp89) ;
tmp90 = atspre_iadd (tmp85, tmp87) ;
tmp84 = atspre_nmod (tmp90, tmp85) ;
return (tmp84) ;
} /* end of [queue_length_01932_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1287(line=71, offs=32) -- 1318(line=72, offs=26)
*/

ats_bool_type
queue_full_01934_int (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp82) ;
ATSlocal (ats_int_type, tmp83) ;
ATSlocal (ats_int_type, tmp91) ;

__ats_lab_queue_full_01934_int:
tmp83 = queue_length_01932_int (arg0) ;
tmp91 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp82 = atspre_ieq (tmp83, tmp91) ;
return (tmp82) ;
} /* end of [queue_full_01934_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1356(line=74, offs=37) -- 1388(line=75, offs=26)
*/

ats_bool_type
queue_available_01933_int (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp94) ;
ATSlocal (ats_int_type, tmp95) ;
ATSlocal (ats_int_type, tmp96) ;

__ats_lab_queue_available_01933_int:
tmp95 = queue_length_01932_int (arg0) ;
tmp96 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp94 = atspre_ilt (tmp95, tmp96) ;
return (tmp94) ;
} /* end of [queue_available_01933_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1225(line=68, offs=33) -- 1252(line=69, offs=22)
*/

ats_bool_type
queue_empty_01935_int (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp99) ;
ATSlocal (ats_int_type, tmp100) ;

__ats_lab_queue_empty_01935_int:
tmp100 = queue_length_01932_int (arg0) ;
tmp99 = atspre_ieq (tmp100, 0) ;
return (tmp99) ;
} /* end of [queue_empty_01935_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1433(line=78, offs=3) -- 1644(line=86, offs=4)
*/

ats_void_type
queue_snapshot_01936_int (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp103) ;
ATSlocal (ats_int_type, tmp104) ;
ATSlocal (ats_int_type, tmp105) ;
ATSlocal (ats_bool_type, tmp106) ;
ATSlocal (ats_int_type, tmp107) ;
ATSlocal (ats_int_type, tmp108) ;
ATSlocal (ats_int_type, tmp109) ;
ATSlocal (ats_int_type, tmp110) ;
ATSlocal (ats_int_type, tmp111) ;
ATSlocal (ats_int_type, tmp112) ;
ATSlocal (int, tmp113) ;

__ats_lab_queue_snapshot_01936_int:
tmp104 = queue_length_01932_int (arg0) ;
/* ats_int_type tmp105 ; */
/* loop initialization */
tmp105 = 0 ;
ats_loop_beg_mac(__ats_lab_3)
tmp106 = atspre_ilt (tmp105, tmp104) ;
if (!tmp106) break ;
tmp110 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp109 = atspre_iadd (tmp110, tmp105) ;
tmp112 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp111 = atspre_iadd (tmp112, 1) ;
tmp108 = atspre_nmod (tmp109, tmp111) ;
tmp113 = ats_caselind_mac(int, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp108]) ;
ats_caselptrind_mac(int, arg1, [tmp105]) = tmp113 ;
/* post update before continue */
__ats_lab_5:
tmp107 = atspre_iadd (tmp105, 1) ;
tmp105 = tmp107 ;
ats_loop_end_mac(__ats_lab_3, __ats_lab_4)
return /* (tmp103) */ ;
} /* end of [queue_snapshot_01936_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 931(line=54, offs=32) -- 982(line=56, offs=2)
*/

int
queue_peek_01930_int (ats_ref_type arg0) {
/* local vardec */
ATSlocal (int, tmp115) ;
ATSlocal (ats_int_type, tmp116) ;

__ats_lab_queue_peek_01930_int:
tmp116 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp115 = ats_caselind_mac(int, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp116]) ;
return (tmp115) ;
} /* end of [queue_peek_01930_int] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1015(line=58, offs=32) -- 1049(line=60, offs=2)
*/

ats_void_type
queue_init_01931_CanMessage (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp120) ;

__ats_lab_queue_init_01931_CanMessage:
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = 0 ;
return /* (tmp120) */ ;
} /* end of [queue_init_01931_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 564(line=37, offs=32) -- 748(line=46, offs=4)
*/

ats_bool_type
queue_push_01928_CanMessage (ats_ref_type arg0, CanMessage arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp123) ;
ATSlocal (ats_int_type, tmp124) ;
ATSlocal (ats_int_type, tmp125) ;
ATSlocal (ats_int_type, tmp126) ;
ATSlocal (ats_int_type, tmp127) ;
ATSlocal (ats_int_type, tmp128) ;
ATSlocal (ats_bool_type, tmp129) ;
ATSlocal (ats_int_type, tmp130) ;

__ats_lab_queue_push_01928_CanMessage:
tmp126 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp125 = atspre_iadd (tmp126, 1) ;
tmp128 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp127 = atspre_iadd (tmp128, 1) ;
tmp124 = atspre_nmod (tmp125, tmp127) ;
tmp130 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp129 = atspre_ieq (tmp124, tmp130) ;
if (tmp129) {
tmp123 = ats_false_bool ;
} else {
ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp124]) = arg1 ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) = tmp124 ;
tmp123 = ats_true_bool ;
} /* end of [if] */
return (tmp123) ;
} /* end of [queue_push_01928_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 780(line=48, offs=31) -- 898(line=52, offs=2)
*/

CanMessage
queue_pop_01929_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (CanMessage, tmp132) ;
ATSlocal (ats_int_type, tmp133) ;
ATSlocal (ats_int_type, tmp134) ;
ATSlocal (ats_int_type, tmp135) ;
ATSlocal (ats_int_type, tmp136) ;
ATSlocal (ats_int_type, tmp137) ;
ATSlocal (CanMessage, tmp138) ;
ATSlocal (ats_int_type, tmp139) ;

__ats_lab_queue_pop_01929_CanMessage:
tmp135 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp134 = atspre_iadd (tmp135, 1) ;
tmp137 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp136 = atspre_iadd (tmp137, 1) ;
tmp133 = atspre_nmod (tmp134, tmp136) ;
tmp139 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp138 = ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp139]) ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = tmp133 ;
tmp132 = tmp138 ;
return (tmp132) ;
} /* end of [queue_pop_01929_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1084(line=62, offs=34) -- 1191(line=66, offs=2)
*/

ats_int_type
queue_length_01932_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp143) ;
ATSlocal (ats_int_type, tmp144) ;
ATSlocal (ats_int_type, tmp145) ;
ATSlocal (ats_int_type, tmp146) ;
ATSlocal (ats_int_type, tmp147) ;
ATSlocal (ats_int_type, tmp148) ;
ATSlocal (ats_int_type, tmp149) ;

__ats_lab_queue_length_01932_CanMessage:
tmp145 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp144 = atspre_iadd (tmp145, 1) ;
tmp147 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp148 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp146 = atspre_isub (tmp147, tmp148) ;
tmp149 = atspre_iadd (tmp144, tmp146) ;
tmp143 = atspre_nmod (tmp149, tmp144) ;
return (tmp143) ;
} /* end of [queue_length_01932_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1287(line=71, offs=32) -- 1318(line=72, offs=26)
*/

ats_bool_type
queue_full_01934_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp141) ;
ATSlocal (ats_int_type, tmp142) ;
ATSlocal (ats_int_type, tmp150) ;

__ats_lab_queue_full_01934_CanMessage:
tmp142 = queue_length_01932_CanMessage (arg0) ;
tmp150 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp141 = atspre_ieq (tmp142, tmp150) ;
return (tmp141) ;
} /* end of [queue_full_01934_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1356(line=74, offs=37) -- 1388(line=75, offs=26)
*/

ats_bool_type
queue_available_01933_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp153) ;
ATSlocal (ats_int_type, tmp154) ;
ATSlocal (ats_int_type, tmp155) ;

__ats_lab_queue_available_01933_CanMessage:
tmp154 = queue_length_01932_CanMessage (arg0) ;
tmp155 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp153 = atspre_ilt (tmp154, tmp155) ;
return (tmp153) ;
} /* end of [queue_available_01933_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1225(line=68, offs=33) -- 1252(line=69, offs=22)
*/

ats_bool_type
queue_empty_01935_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp158) ;
ATSlocal (ats_int_type, tmp159) ;

__ats_lab_queue_empty_01935_CanMessage:
tmp159 = queue_length_01932_CanMessage (arg0) ;
tmp158 = atspre_ieq (tmp159, 0) ;
return (tmp158) ;
} /* end of [queue_empty_01935_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1433(line=78, offs=3) -- 1644(line=86, offs=4)
*/

ats_void_type
queue_snapshot_01936_CanMessage (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp162) ;
ATSlocal (ats_int_type, tmp163) ;
ATSlocal (ats_int_type, tmp164) ;
ATSlocal (ats_bool_type, tmp165) ;
ATSlocal (ats_int_type, tmp166) ;
ATSlocal (ats_int_type, tmp167) ;
ATSlocal (ats_int_type, tmp168) ;
ATSlocal (ats_int_type, tmp169) ;
ATSlocal (ats_int_type, tmp170) ;
ATSlocal (ats_int_type, tmp171) ;
ATSlocal (CanMessage, tmp172) ;

__ats_lab_queue_snapshot_01936_CanMessage:
tmp163 = queue_length_01932_CanMessage (arg0) ;
/* ats_int_type tmp164 ; */
/* loop initialization */
tmp164 = 0 ;
ats_loop_beg_mac(__ats_lab_6)
tmp165 = atspre_ilt (tmp164, tmp163) ;
if (!tmp165) break ;
tmp169 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp168 = atspre_iadd (tmp169, tmp164) ;
tmp171 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp170 = atspre_iadd (tmp171, 1) ;
tmp167 = atspre_nmod (tmp168, tmp170) ;
tmp172 = ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp167]) ;
ats_caselptrind_mac(CanMessage, arg1, [tmp164]) = tmp172 ;
/* post update before continue */
__ats_lab_8:
tmp166 = atspre_iadd (tmp164, 1) ;
tmp164 = tmp166 ;
ats_loop_end_mac(__ats_lab_6, __ats_lab_7)
return /* (tmp162) */ ;
} /* end of [queue_snapshot_01936_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 931(line=54, offs=32) -- 982(line=56, offs=2)
*/

CanMessage
queue_peek_01930_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (CanMessage, tmp174) ;
ATSlocal (ats_int_type, tmp175) ;

__ats_lab_queue_peek_01930_CanMessage:
tmp175 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp174 = ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp175]) ;
return (tmp174) ;
} /* end of [queue_peek_01930_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1015(line=58, offs=32) -- 1049(line=60, offs=2)
*/

ats_void_type
queue_init_01931_test_t (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp179) ;

__ats_lab_queue_init_01931_test_t:
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = 0 ;
return /* (tmp179) */ ;
} /* end of [queue_init_01931_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 564(line=37, offs=32) -- 748(line=46, offs=4)
*/

ats_bool_type
queue_push_01928_test_t (ats_ref_type arg0, test_t arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp182) ;
ATSlocal (ats_int_type, tmp183) ;
ATSlocal (ats_int_type, tmp184) ;
ATSlocal (ats_int_type, tmp185) ;
ATSlocal (ats_int_type, tmp186) ;
ATSlocal (ats_int_type, tmp187) ;
ATSlocal (ats_bool_type, tmp188) ;
ATSlocal (ats_int_type, tmp189) ;

__ats_lab_queue_push_01928_test_t:
tmp185 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp184 = atspre_iadd (tmp185, 1) ;
tmp187 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp186 = atspre_iadd (tmp187, 1) ;
tmp183 = atspre_nmod (tmp184, tmp186) ;
tmp189 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp188 = atspre_ieq (tmp183, tmp189) ;
if (tmp188) {
tmp182 = ats_false_bool ;
} else {
ats_caselind_mac(test_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp183]) = arg1 ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) = tmp183 ;
tmp182 = ats_true_bool ;
} /* end of [if] */
return (tmp182) ;
} /* end of [queue_push_01928_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 780(line=48, offs=31) -- 898(line=52, offs=2)
*/

test_t
queue_pop_01929_test_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (test_t, tmp191) ;
ATSlocal (ats_int_type, tmp192) ;
ATSlocal (ats_int_type, tmp193) ;
ATSlocal (ats_int_type, tmp194) ;
ATSlocal (ats_int_type, tmp195) ;
ATSlocal (ats_int_type, tmp196) ;
ATSlocal (test_t, tmp197) ;
ATSlocal (ats_int_type, tmp198) ;

__ats_lab_queue_pop_01929_test_t:
tmp194 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp193 = atspre_iadd (tmp194, 1) ;
tmp196 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp195 = atspre_iadd (tmp196, 1) ;
tmp192 = atspre_nmod (tmp193, tmp195) ;
tmp198 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp197 = ats_caselind_mac(test_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp198]) ;
ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) = tmp192 ;
tmp191 = tmp197 ;
return (tmp191) ;
} /* end of [queue_pop_01929_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1084(line=62, offs=34) -- 1191(line=66, offs=2)
*/

ats_int_type
queue_length_01932_test_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp202) ;
ATSlocal (ats_int_type, tmp203) ;
ATSlocal (ats_int_type, tmp204) ;
ATSlocal (ats_int_type, tmp205) ;
ATSlocal (ats_int_type, tmp206) ;
ATSlocal (ats_int_type, tmp207) ;
ATSlocal (ats_int_type, tmp208) ;

__ats_lab_queue_length_01932_test_t:
tmp204 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp203 = atspre_iadd (tmp204, 1) ;
tmp206 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_head) ;
tmp207 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp205 = atspre_isub (tmp206, tmp207) ;
tmp208 = atspre_iadd (tmp203, tmp205) ;
tmp202 = atspre_nmod (tmp208, tmp203) ;
return (tmp202) ;
} /* end of [queue_length_01932_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1287(line=71, offs=32) -- 1318(line=72, offs=26)
*/

ats_bool_type
queue_full_01934_test_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp200) ;
ATSlocal (ats_int_type, tmp201) ;
ATSlocal (ats_int_type, tmp209) ;

__ats_lab_queue_full_01934_test_t:
tmp201 = queue_length_01932_test_t (arg0) ;
tmp209 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp200 = atspre_ieq (tmp201, tmp209) ;
return (tmp200) ;
} /* end of [queue_full_01934_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1356(line=74, offs=37) -- 1388(line=75, offs=26)
*/

ats_bool_type
queue_available_01933_test_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp212) ;
ATSlocal (ats_int_type, tmp213) ;
ATSlocal (ats_int_type, tmp214) ;

__ats_lab_queue_available_01933_test_t:
tmp213 = queue_length_01932_test_t (arg0) ;
tmp214 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp212 = atspre_ilt (tmp213, tmp214) ;
return (tmp212) ;
} /* end of [queue_available_01933_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1225(line=68, offs=33) -- 1252(line=69, offs=22)
*/

ats_bool_type
queue_empty_01935_test_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp217) ;
ATSlocal (ats_int_type, tmp218) ;

__ats_lab_queue_empty_01935_test_t:
tmp218 = queue_length_01932_test_t (arg0) ;
tmp217 = atspre_ieq (tmp218, 0) ;
return (tmp217) ;
} /* end of [queue_empty_01935_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1433(line=78, offs=3) -- 1644(line=86, offs=4)
*/

ats_void_type
queue_snapshot_01936_test_t (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp221) ;
ATSlocal (ats_int_type, tmp222) ;
ATSlocal (ats_int_type, tmp223) ;
ATSlocal (ats_bool_type, tmp224) ;
ATSlocal (ats_int_type, tmp225) ;
ATSlocal (ats_int_type, tmp226) ;
ATSlocal (ats_int_type, tmp227) ;
ATSlocal (ats_int_type, tmp228) ;
ATSlocal (ats_int_type, tmp229) ;
ATSlocal (ats_int_type, tmp230) ;
ATSlocal (test_t, tmp231) ;

__ats_lab_queue_snapshot_01936_test_t:
tmp222 = queue_length_01932_test_t (arg0) ;
/* ats_int_type tmp223 ; */
/* loop initialization */
tmp223 = 0 ;
ats_loop_beg_mac(__ats_lab_9)
tmp224 = atspre_ilt (tmp223, tmp222) ;
if (!tmp224) break ;
tmp228 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp227 = atspre_iadd (tmp228, tmp223) ;
tmp230 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_max) ;
tmp229 = atspre_iadd (tmp230, 1) ;
tmp226 = atspre_nmod (tmp227, tmp229) ;
tmp231 = ats_caselind_mac(test_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp226]) ;
ats_caselptrind_mac(test_t, arg1, [tmp223]) = tmp231 ;
/* post update before continue */
__ats_lab_11:
tmp225 = atspre_iadd (tmp223, 1) ;
tmp223 = tmp225 ;
ats_loop_end_mac(__ats_lab_9, __ats_lab_10)
return /* (tmp221) */ ;
} /* end of [queue_snapshot_01936_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 931(line=54, offs=32) -- 982(line=56, offs=2)
*/

test_t
queue_peek_01930_test_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (test_t, tmp233) ;
ATSlocal (ats_int_type, tmp234) ;

__ats_lab_queue_peek_01930_test_t:
tmp234 = ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_tail) ;
tmp233 = ats_caselind_mac(test_t, ats_select_mac(ats_ptrget_mac(anairiats_rec_0, arg0), atslab_elements[0]), [tmp234]) ;
return (tmp233) ;
} /* end of [queue_peek_01930_test_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 2254(line=116, offs=5) -- 3973(line=178, offs=2)
*/

ats_void_type
dummy_0 () {
/* local vardec */
// ATSlocal_void (tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
// ATSlocal_void (tmp3) ;
ATSlocal (ats_bool_type, tmp5) ;
ATSlocal (uint8_t, tmp14) ;
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_int_type, tmp34) ;
ATSlocal (ats_bool_type, tmp35) ;
ATSlocal (ats_bool_type, tmp39) ;
ATSlocal (ats_bool_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp43) ;
// ATSlocal_void (tmp44) ;
ATSlocal (uint8_t, tmp56) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
// ATSlocal_void (tmp61) ;
ATSlocal (ats_bool_type, tmp63) ;
ATSlocal (int, tmp72) ;
ATSlocal (ats_bool_type, tmp81) ;
ATSlocal (ats_int_type, tmp92) ;
ATSlocal (ats_bool_type, tmp93) ;
ATSlocal (ats_bool_type, tmp97) ;
ATSlocal (ats_bool_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp101) ;
// ATSlocal_void (tmp102) ;
ATSlocal (int, tmp114) ;
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;
// ATSlocal_void (tmp119) ;
ATSlocal (CanMessage, tmp121) ;
ATSlocal (ats_bool_type, tmp122) ;
ATSlocal (CanMessage, tmp131) ;
ATSlocal (ats_bool_type, tmp140) ;
ATSlocal (ats_int_type, tmp151) ;
ATSlocal (ats_bool_type, tmp152) ;
ATSlocal (ats_bool_type, tmp156) ;
ATSlocal (ats_bool_type, tmp157) ;
ATSlocal (ats_ptr_type, tmp160) ;
// ATSlocal_void (tmp161) ;
ATSlocal (CanMessage, tmp173) ;
ATSlocal (ats_ptr_type, tmp176) ;
ATSlocal (ats_ptr_type, tmp177) ;
// ATSlocal_void (tmp178) ;
ATSlocal (test_t, tmp180) ;
ATSlocal (ats_bool_type, tmp181) ;
ATSlocal (test_t, tmp190) ;
ATSlocal (ats_bool_type, tmp199) ;
ATSlocal (ats_int_type, tmp210) ;
ATSlocal (ats_bool_type, tmp211) ;
ATSlocal (ats_bool_type, tmp215) ;
ATSlocal (ats_bool_type, tmp216) ;
ATSlocal (ats_ptr_type, tmp219) ;
// ATSlocal_void (tmp220) ;
ATSlocal (test_t, tmp232) ;

__ats_lab_dummy_0:
tmp1 = get_queue () ;
tmp2 = ats_selsin_mac(tmp1, atslab_2) ;
/* tmp3 = */ queue_init_01931_uint8_t (tmp2) ;
tmp5 = queue_push_01928_uint8_t (tmp2, ats_castfn_mac(uint8_t, 10)) ;
tmp14 = queue_pop_01929_uint8_t (tmp2) ;
tmp23 = queue_full_01934_uint8_t (tmp2) ;
tmp34 = queue_length_01932_uint8_t (tmp2) ;
tmp35 = queue_available_01933_uint8_t (tmp2) ;
tmp39 = queue_full_01934_uint8_t (tmp2) ;
tmp40 = queue_empty_01935_uint8_t (tmp2) ;
/* ats_ptr_type tmp43 ; */
/* array allocation on stack */
tmp43 = ATS_ALLOCA2(10, sizeof(uint8_t)) ;
/* tmp44 = */ queue_snapshot_01936_uint8_t (tmp2, tmp43) ;
tmp56 = queue_peek_01930_uint8_t (tmp2) ;
tmp59 = get_queue () ;
tmp60 = ats_selsin_mac(tmp59, atslab_2) ;
/* tmp61 = */ queue_init_01931_int (tmp60) ;
tmp63 = queue_push_01928_int (tmp60, ats_castfn_mac(int, 10)) ;
tmp72 = queue_pop_01929_int (tmp60) ;
tmp81 = queue_full_01934_int (tmp60) ;
tmp92 = queue_length_01932_int (tmp60) ;
tmp93 = queue_available_01933_int (tmp60) ;
tmp97 = queue_full_01934_int (tmp60) ;
tmp98 = queue_empty_01935_int (tmp60) ;
/* ats_ptr_type tmp101 ; */
/* array allocation on stack */
tmp101 = ATS_ALLOCA2(10, sizeof(int)) ;
/* tmp102 = */ queue_snapshot_01936_int (tmp60, tmp101) ;
tmp114 = queue_peek_01930_int (tmp60) ;
tmp117 = get_queue () ;
tmp118 = ats_selsin_mac(tmp117, atslab_2) ;
/* tmp119 = */ queue_init_01931_CanMessage (tmp118) ;
/* CanMessage tmp121 ; */
tmp122 = queue_push_01928_CanMessage (tmp118, tmp121) ;
tmp131 = queue_pop_01929_CanMessage (tmp118) ;
tmp140 = queue_full_01934_CanMessage (tmp118) ;
tmp151 = queue_length_01932_CanMessage (tmp118) ;
tmp152 = queue_available_01933_CanMessage (tmp118) ;
tmp156 = queue_full_01934_CanMessage (tmp118) ;
tmp157 = queue_empty_01935_CanMessage (tmp118) ;
/* ats_ptr_type tmp160 ; */
/* array allocation on stack */
tmp160 = ATS_ALLOCA2(10, sizeof(CanMessage)) ;
/* tmp161 = */ queue_snapshot_01936_CanMessage (tmp118, tmp160) ;
tmp173 = queue_peek_01930_CanMessage (tmp118) ;
tmp176 = get_queue () ;
tmp177 = ats_selsin_mac(tmp176, atslab_2) ;
/* tmp178 = */ queue_init_01931_test_t (tmp177) ;
/* test_t tmp180 ; */
tmp181 = queue_push_01928_test_t (tmp177, tmp180) ;
tmp190 = queue_pop_01929_test_t (tmp177) ;
tmp199 = queue_full_01934_test_t (tmp177) ;
tmp210 = queue_length_01932_test_t (tmp177) ;
tmp211 = queue_available_01933_test_t (tmp177) ;
tmp215 = queue_full_01934_test_t (tmp177) ;
tmp216 = queue_empty_01935_test_t (tmp177) ;
/* ats_ptr_type tmp219 ; */
/* array allocation on stack */
tmp219 = ATS_ALLOCA2(10, sizeof(test_t)) ;
/* tmp220 = */ queue_snapshot_01936_test_t (tmp177, tmp219) ;
tmp232 = queue_peek_01930_test_t (tmp177) ;
return /* (tmp0) */ ;
} /* end of [dummy_0] */

#ifdef _ATS_AVR

#define _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload() 

#else

/*  load function */

extern ats_void_type _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2SATS_2queue_2esats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2unsafe_2edats__staload (void) ;

ats_void_type
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload () {
 int _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload_flag = 0 ;
if (_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload_flag) return ;
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload_flag = 1 ;

_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2SATS_2queue_2esats__staload () ;
// ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2unsafe_2edats__staload () ;

return ;
} /* staload function */


#endif/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__dynload_flag ;

ats_void_type
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__dynload () {
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__dynload_flag = 1 ;
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking  variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [queue_dats.c] */
