/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-1-26: 13h:51m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .h files for avr */
#ifdef _ATS_AVR
#include "ats/basics.h"
#endif /* _ATS_AVR */
/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from ally loaded files */
/* external codes at top */

#include "ats/basics.h"

typedef struct {
    void *bus;
    uint32_t id;
    uint64_t data;
} CanMessage;

typedef struct {
    int i;
    char bytes[8];
} test_t;

 typedef struct {
   int head;
   int tail;
   char elements[];
 } queue_t;

/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_nmod) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ieq) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, get_queue) () ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2SATS_2queue_2esats__sasp__queue = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */

ats_int_type queue_max_length_01929_uint8_t () ;

ats_int_type queue_max_length_01929_CanMessage () ;

ats_void_type queue_init_01933_uint8_t (ats_ref_type arg0) ;

ats_bool_type queue_push_01930_uint8_t (ats_ref_type arg0, uint8_t arg1) ;

uint8_t queue_pop_01931_uint8_t (ats_ref_type arg0) ;

ats_int_type queue_length_01934_uint8_t (ats_ref_type arg0) ;

ats_bool_type queue_full_01936_uint8_t (ats_ref_type arg0) ;

ats_int_type queue_available_01935_uint8_t (ats_ref_type arg0) ;

ats_bool_type queue_empty_01937_uint8_t (ats_ref_type arg0) ;

ats_void_type loop_11 (ats_int_type arg0, ats_ref_type arg1, ats_ref_type arg2) ;

ats_void_type queue_snapshot_01938_uint8_t (ats_ref_type arg0, ats_ref_type arg1) ;

uint8_t queue_peek_01932_uint8_t (ats_ref_type arg0) ;

ats_void_type queue_init_01933_CanMessage (ats_ref_type arg0) ;

ats_bool_type queue_push_01930_CanMessage (ats_ref_type arg0, CanMessage arg1) ;

CanMessage queue_pop_01931_CanMessage (ats_ref_type arg0) ;

ats_int_type queue_length_01934_CanMessage (ats_ref_type arg0) ;

ats_bool_type queue_full_01936_CanMessage (ats_ref_type arg0) ;

ats_int_type queue_available_01935_CanMessage (ats_ref_type arg0) ;

ats_bool_type queue_empty_01937_CanMessage (ats_ref_type arg0) ;

ats_void_type loop_21 (ats_int_type arg0, ats_ref_type arg1, ats_ref_type arg2) ;

ats_void_type queue_snapshot_01938_CanMessage (ats_ref_type arg0, ats_ref_type arg1) ;

CanMessage queue_peek_01932_CanMessage (ats_ref_type arg0) ;

ats_void_type dummy_2 () ;

/* partial value template declarations */
/*  temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 3423(line=158, offs=36) -- 3446(line=158, offs=59)
*/

ats_int_type
queue_max_length_01929_uint8_t () {
/* local vardec */
ATSlocal (ats_int_type, tmp0) ;

__ats_lab_queue_max_length_01929_uint8_t:
tmp0 = ats_castfn_mac(ats_int_type, 513) ;
return (tmp0) ;
} /* end of [queue_max_length_01929_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 3488(line=160, offs=40) -- 3510(line=160, offs=62)
*/

ats_int_type
queue_max_length_01929_CanMessage () {
/* local vardec */
ATSlocal (ats_int_type, tmp1) ;

__ats_lab_queue_max_length_01929_CanMessage:
tmp1 = ats_castfn_mac(ats_int_type, 17) ;
return (tmp1) ;
} /* end of [queue_max_length_01929_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1445(line=81, offs=26) -- 1500(line=84, offs=2)
*/

ats_void_type
queue_init_01933_uint8_t (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp6) ;

__ats_lab_queue_init_01933_uint8_t:
ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) = 0 ;
ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) = 0 ;
return /* (tmp6) */ ;
} /* end of [queue_init_01933_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 799(line=54, offs=26) -- 1091(line=66, offs=4)
*/

ats_bool_type
queue_push_01930_uint8_t (ats_ref_type arg0, uint8_t arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp8) ;
ATSlocal (ats_int_type, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;
ATSlocal (ats_int_type, tmp11) ;
ATSlocal (ats_int_type, tmp12) ;
ATSlocal (ats_bool_type, tmp13) ;
ATSlocal (ats_int_type, tmp14) ;
ATSlocal (ats_int_type, tmp15) ;

__ats_lab_queue_push_01930_uint8_t:
tmp9 = queue_max_length_01929_uint8_t () ;
tmp12 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) ;
tmp11 = atspre_iadd (tmp12, 1) ;
tmp10 = atspre_nmod (tmp11, ats_castfn_mac(ats_int_type, tmp9)) ;
tmp14 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp13 = atspre_ieq (tmp10, tmp14) ;
if (tmp13) {
tmp8 = ats_false_bool ;
} else {
tmp15 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) ;
ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(queue_t, arg0), elements[0]), [tmp15]) = arg1 ;
ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) = tmp10 ;
tmp8 = ats_true_bool ;
} /* end of [if] */
return (tmp8) ;
} /* end of [queue_push_01930_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1117(line=68, offs=25) -- 1340(line=75, offs=2)
*/

uint8_t
queue_pop_01931_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (uint8_t, tmp17) ;
ATSlocal (ats_int_type, tmp18) ;
ATSlocal (ats_int_type, tmp19) ;
ATSlocal (ats_int_type, tmp20) ;
ATSlocal (ats_int_type, tmp21) ;
ATSlocal (uint8_t, tmp22) ;
ATSlocal (ats_int_type, tmp23) ;

__ats_lab_queue_pop_01931_uint8_t:
tmp18 = queue_max_length_01929_uint8_t () ;
tmp21 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp20 = atspre_iadd (tmp21, 1) ;
tmp19 = atspre_nmod (tmp20, ats_castfn_mac(ats_int_type, tmp18)) ;
tmp23 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp22 = ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(queue_t, arg0), elements[0]), [tmp23]) ;
ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) = tmp19 ;
tmp17 = tmp22 ;
return (tmp17) ;
} /* end of [queue_pop_01931_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1529(line=86, offs=28) -- 1722(line=92, offs=2)
*/

ats_int_type
queue_length_01934_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp28) ;
ATSlocal (ats_int_type, tmp29) ;
ATSlocal (ats_int_type, tmp30) ;
ATSlocal (ats_int_type, tmp31) ;
ATSlocal (ats_int_type, tmp32) ;
ATSlocal (ats_int_type, tmp33) ;

__ats_lab_queue_length_01934_uint8_t:
tmp29 = queue_max_length_01929_uint8_t () ;
tmp31 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) ;
tmp32 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp30 = atspre_isub (tmp31, tmp32) ;
tmp33 = atspre_iadd (ats_castfn_mac(ats_int_type, tmp29), tmp30) ;
tmp28 = atspre_nmod (tmp33, ats_castfn_mac(ats_int_type, tmp29)) ;
return (tmp28) ;
} /* end of [queue_length_01934_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1806(line=97, offs=26) -- 1963(line=103, offs=4)
*/

ats_bool_type
queue_full_01936_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp25) ;
ATSlocal (ats_int_type, tmp26) ;
ATSlocal (ats_int_type, tmp27) ;
ATSlocal (ats_int_type, tmp34) ;

__ats_lab_queue_full_01936_uint8_t:
tmp26 = queue_max_length_01929_uint8_t () ;
tmp27 = queue_length_01934_uint8_t (arg0) ;
tmp34 = atspre_isub (ats_castfn_mac(ats_int_type, tmp26), 1) ;
tmp25 = atspre_ieq (tmp27, tmp34) ;
return (tmp25) ;
} /* end of [queue_full_01936_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1995(line=105, offs=31) -- 2152(line=111, offs=4)
*/

ats_int_type
queue_available_01935_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp37) ;
ATSlocal (ats_int_type, tmp38) ;
ATSlocal (ats_int_type, tmp39) ;
ATSlocal (ats_int_type, tmp40) ;

__ats_lab_queue_available_01935_uint8_t:
tmp38 = queue_max_length_01929_uint8_t () ;
tmp39 = atspre_isub (ats_castfn_mac(ats_int_type, tmp38), 1) ;
tmp40 = queue_length_01934_uint8_t (arg0) ;
tmp37 = atspre_isub (tmp39, tmp40) ;
return (tmp37) ;
} /* end of [queue_available_01935_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1750(line=94, offs=27) -- 1777(line=95, offs=22)
*/

ats_bool_type
queue_empty_01937_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp43) ;
ATSlocal (ats_int_type, tmp44) ;

__ats_lab_queue_empty_01937_uint8_t:
tmp44 = queue_length_01934_uint8_t (arg0) ;
tmp43 = atspre_ieq (tmp44, 0) ;
return (tmp43) ;
} /* end of [queue_empty_01937_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 2515(line=122, offs=9) -- 3044(line=138, offs=8)
*/

ats_void_type
loop_11 (ats_int_type arg0, ats_ref_type arg1, ats_ref_type arg2) {
/* local vardec */
// ATSlocal_void (tmp49) ;
ATSlocal (ats_int_type, tmp50) ;
ATSlocal (ats_int_type, tmp51) ;
ATSlocal (ats_int_type, tmp52) ;
ATSlocal (ats_int_type, tmp53) ;
ATSlocal (ats_int_type, tmp54) ;
ATSlocal (uint8_t, tmp55) ;
ATSlocal (ats_bool_type, tmp56) ;
ATSlocal (ats_int_type, tmp57) ;
ATSlocal (ats_int_type, tmp58) ;

__ats_lab_loop_11:
tmp50 = queue_length_01934_uint8_t (arg1) ;
tmp51 = queue_max_length_01929_uint8_t () ;
tmp54 = ats_select_mac(ats_ptrget_mac(queue_t, arg1), tail) ;
tmp53 = atspre_iadd (tmp54, arg0) ;
tmp52 = atspre_nmod (tmp53, ats_castfn_mac(ats_int_type, tmp51)) ;
tmp55 = ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(queue_t, arg1), elements[0]), [tmp52]) ;
ats_caselptrind_mac(uint8_t, arg2, [arg0]) = tmp55 ;
tmp57 = atspre_iadd (arg0, 1) ;
tmp56 = atspre_igte (tmp57, tmp50) ;
if (tmp56) {
/* empty */
} else {
tmp58 = atspre_iadd (arg0, 1) ;
arg0 = tmp58 ;
arg1 = arg1 ;
arg2 = arg2 ;
goto __ats_lab_loop_11 ; // tail call
} /* end of [if] */
return /* (tmp49) */ ;
} /* end of [loop_11] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 2192(line=114, offs=3) -- 3080(line=140, offs=2)
*/

ats_void_type
queue_snapshot_01938_uint8_t (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp47) ;
ATSlocal (ats_int_type, tmp48) ;

__ats_lab_queue_snapshot_01938_uint8_t:
tmp48 = queue_length_01934_uint8_t (arg0) ;
/* tmp47 = */ loop_11 (0, arg0, arg1) ;
return /* (tmp47) */ ;
} /* end of [queue_snapshot_01938_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1367(line=77, offs=26) -- 1418(line=79, offs=2)
*/

uint8_t
queue_peek_01932_uint8_t (ats_ref_type arg0) {
/* local vardec */
ATSlocal (uint8_t, tmp60) ;
ATSlocal (ats_int_type, tmp61) ;

__ats_lab_queue_peek_01932_uint8_t:
tmp61 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp60 = ats_caselind_mac(uint8_t, ats_select_mac(ats_ptrget_mac(queue_t, arg0), elements[0]), [tmp61]) ;
return (tmp60) ;
} /* end of [queue_peek_01932_uint8_t] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1445(line=81, offs=26) -- 1500(line=84, offs=2)
*/

ats_void_type
queue_init_01933_CanMessage (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp65) ;

__ats_lab_queue_init_01933_CanMessage:
ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) = 0 ;
ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) = 0 ;
return /* (tmp65) */ ;
} /* end of [queue_init_01933_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 799(line=54, offs=26) -- 1091(line=66, offs=4)
*/

ats_bool_type
queue_push_01930_CanMessage (ats_ref_type arg0, CanMessage arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp68) ;
ATSlocal (ats_int_type, tmp69) ;
ATSlocal (ats_int_type, tmp70) ;
ATSlocal (ats_int_type, tmp71) ;
ATSlocal (ats_int_type, tmp72) ;
ATSlocal (ats_bool_type, tmp73) ;
ATSlocal (ats_int_type, tmp74) ;
ATSlocal (ats_int_type, tmp75) ;

__ats_lab_queue_push_01930_CanMessage:
tmp69 = queue_max_length_01929_CanMessage () ;
tmp72 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) ;
tmp71 = atspre_iadd (tmp72, 1) ;
tmp70 = atspre_nmod (tmp71, ats_castfn_mac(ats_int_type, tmp69)) ;
tmp74 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp73 = atspre_ieq (tmp70, tmp74) ;
if (tmp73) {
tmp68 = ats_false_bool ;
} else {
tmp75 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) ;
ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(queue_t, arg0), elements[0]), [tmp75]) = arg1 ;
ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) = tmp70 ;
tmp68 = ats_true_bool ;
} /* end of [if] */
return (tmp68) ;
} /* end of [queue_push_01930_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1117(line=68, offs=25) -- 1340(line=75, offs=2)
*/

CanMessage
queue_pop_01931_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (CanMessage, tmp77) ;
ATSlocal (ats_int_type, tmp78) ;
ATSlocal (ats_int_type, tmp79) ;
ATSlocal (ats_int_type, tmp80) ;
ATSlocal (ats_int_type, tmp81) ;
ATSlocal (CanMessage, tmp82) ;
ATSlocal (ats_int_type, tmp83) ;

__ats_lab_queue_pop_01931_CanMessage:
tmp78 = queue_max_length_01929_CanMessage () ;
tmp81 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp80 = atspre_iadd (tmp81, 1) ;
tmp79 = atspre_nmod (tmp80, ats_castfn_mac(ats_int_type, tmp78)) ;
tmp83 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp82 = ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(queue_t, arg0), elements[0]), [tmp83]) ;
ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) = tmp79 ;
tmp77 = tmp82 ;
return (tmp77) ;
} /* end of [queue_pop_01931_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1529(line=86, offs=28) -- 1722(line=92, offs=2)
*/

ats_int_type
queue_length_01934_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp88) ;
ATSlocal (ats_int_type, tmp89) ;
ATSlocal (ats_int_type, tmp90) ;
ATSlocal (ats_int_type, tmp91) ;
ATSlocal (ats_int_type, tmp92) ;
ATSlocal (ats_int_type, tmp93) ;

__ats_lab_queue_length_01934_CanMessage:
tmp89 = queue_max_length_01929_CanMessage () ;
tmp91 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), head) ;
tmp92 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp90 = atspre_isub (tmp91, tmp92) ;
tmp93 = atspre_iadd (ats_castfn_mac(ats_int_type, tmp89), tmp90) ;
tmp88 = atspre_nmod (tmp93, ats_castfn_mac(ats_int_type, tmp89)) ;
return (tmp88) ;
} /* end of [queue_length_01934_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1806(line=97, offs=26) -- 1963(line=103, offs=4)
*/

ats_bool_type
queue_full_01936_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp85) ;
ATSlocal (ats_int_type, tmp86) ;
ATSlocal (ats_int_type, tmp87) ;
ATSlocal (ats_int_type, tmp94) ;

__ats_lab_queue_full_01936_CanMessage:
tmp86 = queue_max_length_01929_CanMessage () ;
tmp87 = queue_length_01934_CanMessage (arg0) ;
tmp94 = atspre_isub (ats_castfn_mac(ats_int_type, tmp86), 1) ;
tmp85 = atspre_ieq (tmp87, tmp94) ;
return (tmp85) ;
} /* end of [queue_full_01936_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1995(line=105, offs=31) -- 2152(line=111, offs=4)
*/

ats_int_type
queue_available_01935_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp97) ;
ATSlocal (ats_int_type, tmp98) ;
ATSlocal (ats_int_type, tmp99) ;
ATSlocal (ats_int_type, tmp100) ;

__ats_lab_queue_available_01935_CanMessage:
tmp98 = queue_max_length_01929_CanMessage () ;
tmp99 = atspre_isub (ats_castfn_mac(ats_int_type, tmp98), 1) ;
tmp100 = queue_length_01934_CanMessage (arg0) ;
tmp97 = atspre_isub (tmp99, tmp100) ;
return (tmp97) ;
} /* end of [queue_available_01935_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1750(line=94, offs=27) -- 1777(line=95, offs=22)
*/

ats_bool_type
queue_empty_01937_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp103) ;
ATSlocal (ats_int_type, tmp104) ;

__ats_lab_queue_empty_01937_CanMessage:
tmp104 = queue_length_01934_CanMessage (arg0) ;
tmp103 = atspre_ieq (tmp104, 0) ;
return (tmp103) ;
} /* end of [queue_empty_01937_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 2515(line=122, offs=9) -- 3044(line=138, offs=8)
*/

ats_void_type
loop_21 (ats_int_type arg0, ats_ref_type arg1, ats_ref_type arg2) {
/* local vardec */
// ATSlocal_void (tmp109) ;
ATSlocal (ats_int_type, tmp110) ;
ATSlocal (ats_int_type, tmp111) ;
ATSlocal (ats_int_type, tmp112) ;
ATSlocal (ats_int_type, tmp113) ;
ATSlocal (ats_int_type, tmp114) ;
ATSlocal (CanMessage, tmp115) ;
ATSlocal (ats_bool_type, tmp116) ;
ATSlocal (ats_int_type, tmp117) ;
ATSlocal (ats_int_type, tmp118) ;

__ats_lab_loop_21:
tmp110 = queue_length_01934_CanMessage (arg1) ;
tmp111 = queue_max_length_01929_CanMessage () ;
tmp114 = ats_select_mac(ats_ptrget_mac(queue_t, arg1), tail) ;
tmp113 = atspre_iadd (tmp114, arg0) ;
tmp112 = atspre_nmod (tmp113, ats_castfn_mac(ats_int_type, tmp111)) ;
tmp115 = ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(queue_t, arg1), elements[0]), [tmp112]) ;
ats_caselptrind_mac(CanMessage, arg2, [arg0]) = tmp115 ;
tmp117 = atspre_iadd (arg0, 1) ;
tmp116 = atspre_igte (tmp117, tmp110) ;
if (tmp116) {
/* empty */
} else {
tmp118 = atspre_iadd (arg0, 1) ;
arg0 = tmp118 ;
arg1 = arg1 ;
arg2 = arg2 ;
goto __ats_lab_loop_21 ; // tail call
} /* end of [if] */
return /* (tmp109) */ ;
} /* end of [loop_21] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 2192(line=114, offs=3) -- 3080(line=140, offs=2)
*/

ats_void_type
queue_snapshot_01938_CanMessage (ats_ref_type arg0, ats_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp107) ;
ATSlocal (ats_int_type, tmp108) ;

__ats_lab_queue_snapshot_01938_CanMessage:
tmp108 = queue_length_01934_CanMessage (arg0) ;
/* tmp107 = */ loop_21 (0, arg0, arg1) ;
return /* (tmp107) */ ;
} /* end of [queue_snapshot_01938_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 1367(line=77, offs=26) -- 1418(line=79, offs=2)
*/

CanMessage
queue_peek_01932_CanMessage (ats_ref_type arg0) {
/* local vardec */
ATSlocal (CanMessage, tmp120) ;
ATSlocal (ats_int_type, tmp121) ;

__ats_lab_queue_peek_01932_CanMessage:
tmp121 = ats_select_mac(ats_ptrget_mac(queue_t, arg0), tail) ;
tmp120 = ats_caselind_mac(CanMessage, ats_select_mac(ats_ptrget_mac(queue_t, arg0), elements[0]), [tmp121]) ;
return (tmp120) ;
} /* end of [queue_peek_01932_CanMessage] */

/*
// /home/wdblair/work/ats/cantranslator/src/ats/DATS/queue.dats: 3809(line=175, offs=5) -- 5524(line=241, offs=2)
*/

ats_void_type
dummy_2 () {
/* local vardec */
// ATSlocal_void (tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
// ATSlocal_void (tmp5) ;
ATSlocal (ats_bool_type, tmp7) ;
ATSlocal (uint8_t, tmp16) ;
ATSlocal (ats_bool_type, tmp24) ;
ATSlocal (ats_int_type, tmp35) ;
ATSlocal (ats_int_type, tmp36) ;
ATSlocal (ats_bool_type, tmp41) ;
ATSlocal (ats_bool_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp45) ;
// ATSlocal_void (tmp46) ;
ATSlocal (uint8_t, tmp59) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
// ATSlocal_void (tmp64) ;
ATSlocal (CanMessage, tmp66) ;
ATSlocal (ats_bool_type, tmp67) ;
ATSlocal (CanMessage, tmp76) ;
ATSlocal (ats_bool_type, tmp84) ;
ATSlocal (ats_int_type, tmp95) ;
ATSlocal (ats_int_type, tmp96) ;
ATSlocal (ats_bool_type, tmp101) ;
ATSlocal (ats_bool_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp105) ;
// ATSlocal_void (tmp106) ;
ATSlocal (CanMessage, tmp119) ;

__ats_lab_dummy_2:
tmp3 = get_queue () ;
tmp4 = ats_selsin_mac(tmp3, atslab_2) ;
/* tmp5 = */ queue_init_01933_uint8_t (tmp4) ;
tmp7 = queue_push_01930_uint8_t (tmp4, ats_castfn_mac(uint8_t, 10)) ;
tmp16 = queue_pop_01931_uint8_t (tmp4) ;
tmp24 = queue_full_01936_uint8_t (tmp4) ;
tmp35 = queue_length_01934_uint8_t (tmp4) ;
tmp36 = queue_available_01935_uint8_t (tmp4) ;
tmp41 = queue_full_01936_uint8_t (tmp4) ;
tmp42 = queue_empty_01937_uint8_t (tmp4) ;
/* ats_ptr_type tmp45 ; */
/* array allocation on stack */
tmp45 = ATS_ALLOCA2(10, sizeof(uint8_t)) ;
/* tmp46 = */ queue_snapshot_01938_uint8_t (tmp4, tmp45) ;
tmp59 = queue_peek_01932_uint8_t (tmp4) ;
tmp62 = get_queue () ;
tmp63 = ats_selsin_mac(tmp62, atslab_2) ;
/* tmp64 = */ queue_init_01933_CanMessage (tmp63) ;
/* CanMessage tmp66 ; */
tmp67 = queue_push_01930_CanMessage (tmp63, tmp66) ;
tmp76 = queue_pop_01931_CanMessage (tmp63) ;
tmp84 = queue_full_01936_CanMessage (tmp63) ;
tmp95 = queue_length_01934_CanMessage (tmp63) ;
tmp96 = queue_available_01935_CanMessage (tmp63) ;
tmp101 = queue_full_01936_CanMessage (tmp63) ;
tmp102 = queue_empty_01937_CanMessage (tmp63) ;
/* ats_ptr_type tmp105 ; */
/* array allocation on stack */
tmp105 = ATS_ALLOCA2(10, sizeof(CanMessage)) ;
/* tmp106 = */ queue_snapshot_01938_CanMessage (tmp63, tmp105) ;
tmp119 = queue_peek_01932_CanMessage (tmp63) ;
return /* (tmp2) */ ;
} /* end of [dummy_2] */

#ifdef _ATS_AVR

#define _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload() 

#else

/*  load function */

// extern ats_void_type _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2SATS_2queue_2esats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2unsafe_2edats__staload (void) ;

ats_void_type
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload () {
 int _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload_flag = 0 ;
if (_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload_flag) return ;
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload_flag = 1 ;

// _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2SATS_2queue_2esats__staload () ;
// ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2unsafe_2edats__staload () ;

return ;
} /* staload function */


#endif/* dynamic load function */

// dynload flag declaration
// extern ats_int_type _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__dynload_flag ;

ats_void_type
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__dynload () {
// _2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__dynload_flag = 1 ;
_2home_2wdblair_2work_2ats_2cantranslator_2src_2ats_2DATS_2queue_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking  variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */

  ats_ptr_type get_queue() {
    return NULL;
  }

/* external codes at bot */

/* ****** ****** */

/* end of [queue_dats.c] */
